name: Playwright Tests
on:
  push:
    branches: [ main, master ]

jobs:
    test-playwright:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Instalar node
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Bajar código
              uses: actions/checkout@v4

            - name: Instalar dependencias
              run: npm ci

            - name: Instala chromium
              run: npx playwright install chromium --with-deps
              
            - name: Levantamos aplicación
              run: npm run dev &

            - name: Ejecuta test
              run: npx playwright test

            - name: Sube el reporte
              uses: actions/upload-artifact@v4
              with:
                name: report-test
                path: playwright-report/

